# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-01 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='dll',
        ),
        migrations.AddField(
            model_name='api',
            name='dll',
            field=models.ManyToManyField(blank=True, null=True, to='winapi.Dll'),
        ),
        migrations.AlterField(
            model_name='api',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
