# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-01 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winapi', '0002_auto_20170601_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='dll',
            field=models.ManyToManyField(blank=True, to='winapi.Dll'),
        ),
    ]
