# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-12 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winapi', '0003_auto_20170601_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='category',
        ),
        migrations.AlterField(
            model_name='dll',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
