# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-07-02 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('winapi', '0006_malwareapicall'),
    ]

    operations = [
        migrations.CreateModel(
            name='MalwareAPICallExcutionTrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('malware_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sha256', models.CharField(blank=True, max_length=100, null=True)),
                ('api', models.ManyToManyField(to='winapi.API')),
                ('dll', models.ManyToManyField(blank=True, to='winapi.Dll')),
            ],
        ),
        migrations.RemoveField(
            model_name='malwareapicall',
            name='malware_name',
        ),
        migrations.RemoveField(
            model_name='malwareapicall',
            name='sha256',
        ),
        migrations.AddField(
            model_name='malwareapicall',
            name='malware_excution_trace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='winapi.MalwareAPICallExcutionTrace'),
        ),
    ]
